name: sha_env
description: Yet another DotEnv handling library for Dart but all the other gave me headaches.
version: 0.0.1
homepage: https://github.com/shalien/sha_env
documentation: https://shalien.github.io/sha_env/


environment:
  sdk: '>=2.16.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  path: ^1.8.2
