name: sha_env
description: Yet another DotEnv handling library for Dart but all the other gave me headaches.
version: 0.0.3
homepage: https://github.com/shalien/sha_env
documentation: https://shalien.github.io/sha_env/


environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  meta: ^1.9.1
  path: ^1.8.2
